# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tasks.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"W\n\x04Task\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x1d\n\x06status\x18\x04 \x01(\x0e\x32\r.tasks.Status\"7\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"/\n\x12\x43reateTaskResponse\x12\x19\n\x04task\x18\x01 \x01(\x0b\x32\x0b.tasks.Task\"\x12\n\x10ListTasksRequest\".\n\x11ListTasksResponse\x12\x19\n\x04task\x18\x01 \x01(\x0b\x32\x0b.tasks.Task\"d\n\x11UpdateTaskRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x1d\n\x06status\x18\x04 \x01(\x0e\x32\r.tasks.Status\"/\n\x12UpdateTaskResponse\x12\x19\n\x04task\x18\x01 \x01(\x0b\x32\x0b.tasks.Task\"!\n\x11\x44\x65leteTaskRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x14\n\x12\x44\x65leteTaskResponse*\'\n\x06Status\x12\x08\n\x04TODO\x10\x00\x12\t\n\x05\x44OING\x10\x01\x12\x08\n\x04\x44ONE\x10\x02\x32\x98\x02\n\x0bTaskService\x12\x41\n\nCreateTask\x12\x18.tasks.CreateTaskRequest\x1a\x19.tasks.CreateTaskResponse\x12@\n\tListTasks\x12\x17.tasks.ListTasksRequest\x1a\x18.tasks.ListTasksResponse0\x01\x12\x41\n\nUpdateTask\x12\x18.tasks.UpdateTaskRequest\x1a\x19.tasks.UpdateTaskResponse\x12\x41\n\nDeleteTask\x12\x18.tasks.DeleteTaskRequest\x1a\x19.tasks.DeleteTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=493
  _globals['_STATUS']._serialized_end=532
  _globals['_TASK']._serialized_start=22
  _globals['_TASK']._serialized_end=109
  _globals['_CREATETASKREQUEST']._serialized_start=111
  _globals['_CREATETASKREQUEST']._serialized_end=166
  _globals['_CREATETASKRESPONSE']._serialized_start=168
  _globals['_CREATETASKRESPONSE']._serialized_end=215
  _globals['_LISTTASKSREQUEST']._serialized_start=217
  _globals['_LISTTASKSREQUEST']._serialized_end=235
  _globals['_LISTTASKSRESPONSE']._serialized_start=237
  _globals['_LISTTASKSRESPONSE']._serialized_end=283
  _globals['_UPDATETASKREQUEST']._serialized_start=285
  _globals['_UPDATETASKREQUEST']._serialized_end=385
  _globals['_UPDATETASKRESPONSE']._serialized_start=387
  _globals['_UPDATETASKRESPONSE']._serialized_end=434
  _globals['_DELETETASKREQUEST']._serialized_start=436
  _globals['_DELETETASKREQUEST']._serialized_end=469
  _globals['_DELETETASKRESPONSE']._serialized_start=471
  _globals['_DELETETASKRESPONSE']._serialized_end=491
  _globals['_TASKSERVICE']._serialized_start=535
  _globals['_TASKSERVICE']._serialized_end=815
# @@protoc_insertion_point(module_scope)
